version: "3.8"
   
services:
  redis:
    image: redis:7-alpine

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/schedule
    ports:
      - "8000:8000"
